INSERT INTO pizza.USER (NAME, PASSWORD, ACCESS) VALUES ('user', '123', 'USER');
INSERT INTO pizza.USER (NAME, PASSWORD, ACCESS) VALUES ('admin', '123', 'ADMIN');
INSERT INTO pizza.USER (NAME, PASSWORD, ACCESS) VALUES ('denis', 'denis', 'USER');
INSERT INTO pizza.USER (NAME, PASSWORD, ACCESS) VALUES ('blackmore', 'blackmore', 'ADMIN');
INSERT INTO pizza.USER (NAME, PASSWORD, ACCESS) VALUES ('ritchie', 'ritchie', 'USER');
INSERT INTO pizza.USER (NAME, PASSWORD, ACCESS) VALUES ('jack', 'jack', 'USER');