INSERT INTO pizza.COURSE_CATEGORY (COURSE_TYPE) VALUES ('pizza');
INSERT INTO pizza.COURSE_CATEGORY (COURSE_TYPE) VALUES ('drink');
INSERT INTO pizza.COURSE_CATEGORY (COURSE_TYPE) VALUES ('soup');
INSERT INTO pizza.COURSE_CATEGORY (COURSE_TYPE) VALUES ('desert');
INSERT INTO pizza.COURSE_CATEGORY (COURSE_TYPE) VALUES ('other');